# Tell Travis you want a Python environment to test in
language: python
python:
  - "2.7"
install:
   # Install dependencies
  - pip install coveralls
script:
  - coverage run quicktest.py django_obit_desk2
after_success:
  - coveralls
